### ISSUE TITLE
Setup appveyor CI

### ISSUE THREAD

**Issue by binki** [benjamingr/tmp-promise#13]
See #12. appveyor is a CI that lets you run tests on Windows. This is particular useful with things that get closer to touching system APIs and especially APIs which Windows does wrong like FS stuff such as temporary files. Now, I don’t think this exact package does anything Windows specific, but having a Windows CI to help and perhaps even identify issues with dependencies could be really helpful and increase the confidence with which people could use this repo—as supporting all platforms is a really appealing thing.

**Comment by benjamingr** [comment]
Closing for stale, sorry. Feel free to tackle this again if you want to.
