### ISSUE TITLE
cleanup should not fail when temp file removed

### ISSUE THREAD

**Issue by wmertens** [benjamingr/tmp-promise#18]
I'm using `.withFile()` to guard a file download-and-move-into-place, but that fails after it completes because it wants to delete the temp file which is already gone.

In the regular `node-tmp`, I suppose I would not be calling cleanup after the move succeeds, but with `withFile` I don't have a choice.

I think `.withFile()` should catch and ignore `ENOENT` errors.

**Comment by benjamingr** [comment]
Thanks for the report, taking a look.

**Comment by benjamingr** [comment]
Hey, it looks like this issue has already been fixed in upstream node-tmp, I'll update the version in package.json and do a release https://github.com/raszi/node-tmp/issues/115

**Comment by wmertens** [comment]
Sweet! ⚡️ Super speedy too :)

**Comment by benjamingr** [comment]
I've published 1.0.4, let me know if the issue has been resolved on your end, thanks for the report.

**Comment by wmertens** [comment]
It works nicely, thanks!
