### ISSUE TITLE
Publish typescript declarations

### ISSUE THREAD

**Issue by dyst5422** [benjamingr/tmp-promise#21]
I see that there are declarations in the repo, but they haven't been published to NPM. When could that happen?

**Comment by dlee-nvisia** [comment]
On my original PR #19 @benjamingr mentioned that he'd be able to push a release "after the node.js summit". It appears that is from 7/23 - 7/27.

In the meantime, I've been using direct git access. In case you want to do this as well, I pushed up a tag (with my guess at a version number) to my branch, in case you want to start using them now.

"tmp-promise": "git+https://github.com/dlee-nvisia/tmp-promise.git#1.0.5-pre",

**Comment by benjamingr** [comment]
Sorry, forgot about this - published 1.0.5!
