### ISSUE TITLE
Not removing file

### ISSUE THREAD

**Issue by NiallBunting** [benjamingr/tmp-promise#22]
If I run the following (node v8.11.1, tmp-promise v1.0.5):
```
var tmp = require('tmp-promise');
tmp.file().then(o => {console.log(o.path);}).then(v => {});
```

It seems to leave the temporary file and not delete it, if I list the directory that the path outputs.

I thought the expected behaviour was to delete the file once the promise is complete?

**Comment by benjamingr** [comment]
@NiallBunting thanks for opening an issue, you're looking either for disposers (`withFile`) which removes the file when the promise is resolved or you're looking for calling `cleanup` in order to remove it.

```js
import { withFile } from 'tmp-promise'

withFile(async ({path, fd}) => {
  // when this function returns or throws - release the file 
  await doSomethingWithFile(db);
});
```

**Comment by benjamingr** [comment]
If that did not answer your question - please do speak up though - and I'll reopen it, I just like keeping things tidy.

**Comment by NiallBunting** [comment]
@benjamingr I think in that case the README could be a bit clearer, since the following makes it sounds like it will be autocleaned up:
```
  // If we don't need the file anymore we could manually call cleanup
  // But that is not necessary if we didn't pass the keep option because the library
  // will clean after itself.
```

**Comment by benjamingr** [comment]
It's supposed to be handled by the underlying `tmp` library https://github.com/raszi/node-tmp/blob/master/lib/tmp.js#L586
