### ISSUE TITLE
Use GitHub releases

### ISSUE THREAD

**Issue by ehmicky** [benjamingr/tmp-promise#37]
Great project!

Some users like me use RSS feed readers to catch up with new releases.

However this is not possible with this repository, as it only works when there are GitHub releases. GitHub automatically create releases when Git tags are pushed, so simply adding Git tags should do the work. 

There are also some tools that simplify this process such as [`release-it`](https://github.com/release-it/release-it). 

Thanks!

**Comment by benjamingr** [comment]
Sounds good to me - PR welcome :]

**Comment by ehmicky** [comment]
Adding git tags would be done on the command line before `npm publish`, so this would not need a PR.

**Comment by benjamingr** [comment]
I meant more in line of a `publish` script that does an `npm bump` with a git tag and an `npm publish`

**Comment by ehmicky** [comment]
I am unfortunately not sure I will have time for a PR at the moment. Sorry!

**Comment by benjamingr** [comment]
Closed in 993403581c09b63b88f57e4ed7f5e558d98afacc thanks.
