### ISSUE TITLE
Auto-cleanup doesn't work

### ISSUE THREAD

**Issue by whmountains** [benjamingr/tmp-promise#6]
Auto-cleanup directories isn't working for me.  Here's what I'm doing:

~~~javascript
tmp.dir({
    dir: '/tmp',
    unsafeCleanup: true
})
// and a long chain of .then
~~~
I *am* using the "unsafe cleanup" feature.

**Comment by benjamingr** [comment]
Thanks for fixing this and the PR! 

(By the way, I recommend using the `withDir` function)

**Comment by whmountains** [comment]
This issue still happens even with the fixes from #5.  I haven't looked into why it's happening but I'm just resorting to manual cleanup for now.

**Comment by whmountains** [comment]
Oh, I missed that the automatic cleanup only happens using the `withDir` function.  Sorry about that.

**Comment by benjamingr** [comment]
@whmountains 

Automatic cleanup should happen even without `withDir` if you do:

`tmp.setGracefulCleanup();`

Some people (like me) prefer not having magic code that's run on `unhandledRejection` so the disposer pattern is implemented for `withDir` with:

```js
tmp.withDir(path => {
    // access the directory here, outside of this scope it is automatically cleaned
    return aPromise; // the dir gets deleted after a promise you return from here resolve.
});

```

**Comment by whmountains** [comment]
Okay.  That makes more sense.  Thanks for filling me in.

Also thank you for adding me to the repo.  That's the first time that's happened to me!
